name: Limpiar todas las ejecuciones de workflows

on:
  workflow_dispatch:

jobs:
  clean_workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Eliminar todas las ejecuciones de workflows
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.ELEVATED_GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
